module.exports = {
  ConversationStates: {
    STOPPED : 'STOPPED',
    AVAILABLE : 'AVAILABLE',
    UNAVAILABLE : 'UNAVAILABLE',
  
    USER_READY : 'USER_READY',
    USER_SPEAKING : 'USER_SPEAKING',
    USER_SILENCE : 'USER_SILENCE',
    USER_DONE_SPEAKING : 'USER_DONE_SPEAKING',
    
    ASSISTANT_THINKING : 'ASSISTANT_THINKING',
    ASSISTANT_SPEAKING : 'ASSISTANT_SPEAKING',
    ASSISTANT_DONE_SPEAKING : 'ASSISTANT_DONE_SPEAKING',
  }
}